program: ./scripts/train.py
project: wne-masters-thesis-testing
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "./configs/experiments/temporal-fusion-btcusdt-quantile.yaml"
method: random
metric:
  goal: maximize
  name: val_loss
parameters:
  past_window:
    distribution: int_uniform
    min: 5
    max: 100
  batch_size:
    values: [64, 128, 256]
  model:
    parameters:
      name:
        value: "TemporalFusionTransoformer"
      share_single_variable_networks:
        value: false
      hidden_size:
        values: [128, 256, 512, 1024]
      dropout:
        values: [0.0, 0.1, 0.2, 0.3, 0.4]
      attention_head_size:
        values: [1, 2, 4, 6]
      hidden_continuous_size: 
        values: [4, 8, 16, 32]
      learning_rate:
        values: [0.01, 0.001, 0.0005, 0.0001]
      optimizer:
        values: ["Adam", "RMSProp", "Adagrad"]